"""ComfyUI-Sharp nodes aggregation."""

from .load_model import NODE_CLASS_MAPPINGS as LOAD_MODEL_MAPPINGS
from .load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_MODEL_DISPLAY_MAPPINGS
from .predict import NODE_CLASS_MAPPINGS as PREDICT_MAPPINGS
from .predict import NODE_DISPLAY_NAME_MAPPINGS as PREDICT_DISPLAY_MAPPINGS
from .load_image_exif import NODE_CLASS_MAPPINGS as LOAD_IMAGE_EXIF_MAPPINGS
from .load_image_exif import NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_EXIF_DISPLAY_MAPPINGS
from .spag_predict import NODE_CLASS_MAPPINGS as SPAG_MAPPINGS
from .spag_predict import NODE_DISPLAY_NAME_MAPPINGS as SPAG_DISPLAY_MAPPINGS

# Aggregate all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LOAD_MODEL_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PREDICT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LOAD_IMAGE_EXIF_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SPAG_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MODEL_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREDICT_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_IMAGE_EXIF_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SPAG_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
